version: '3.9'

services:

  appium1:
    image: appium/appium
    container_name: appium_server_1
    privileged: true
    ports:
      - "4723:4723"
    environment:
      - APPIUM_SESSION_OVERRIDE=true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    restart: always

  appium2:
    image: appium/appium
    container_name: appium_server_2
    privileged: true
    ports:
      - "4725:4723"
    environment:
      - APPIUM_SESSION_OVERRIDE=true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    restart: always

  python_runner:
    build:
      context: ./app
      dockerfile: ../python-runner.Dockerfile
    container_name: python_runner
    volumes:
      - ./app:/app
    environment:
      - ENV_FILE=.env
    restart: always
    depends_on:
      - appium1
      - appium2
